### ISSUE TITLE
我运行train_FGVC_Aircraft_ResNet50.py报错说我显存不够，但是我16g显存和24g都运行了还是这样

### ISSUE THREAD

**Issue by lypliuyouping** [Dichao-Liu/CMAL#4]
你好，我电脑3060，16g显存运行train_FGVC_Aircraft_ResNet50.py报错了请问是什么原因呢

==> Preparing data..
Traceback (most recent call last):
  File "train_FGVC_Aircraft_ResNet50.py", line 343, in <module>
    data_path = data_path)         # the saved model where you want to resume the training
  File "train_FGVC_Aircraft_ResNet50.py", line 156, in train
    netp = torch.nn.DataParallel(net, device_ids=[0])
  File "/home/myy/anaconda3/envs/pytorch-myy/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 139, in __init__
    self.module.cuda(device_ids[0])
  File "/home/myy/anaconda3/envs/pytorch-myy/lib/python3.7/site-packages/torch/nn/modules/module.py", line 458, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/myy/anaconda3/envs/pytorch-myy/lib/python3.7/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  File "/home/myy/anaconda3/envs/pytorch-myy/lib/python3.7/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  File "/home/myy/anaconda3/envs/pytorch-myy/lib/python3.7/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  File "/home/myy/anaconda3/envs/pytorch-myy/lib/python3.7/site-packages/torch/nn/modules/module.py", line 376, in _apply
    param_applied = fn(param)
  File "/home/myy/anaconda3/envs/pytorch-myy/lib/python3.7/site-packages/torch/nn/modules/module.py", line 458, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory

**Comment by Dichao-Liu** [comment]
你好，我刚才试了一下。我用的11g的1080ti，代码用的是直接下载的我这个GitHub的代码，并不会报显存不够的错。请问是不是Batch Size比我的原代码里的大。

**Comment by lypliuyouping** [comment]
代码我没改的，就用了官网的数据集直接报错显存不足




1449917271
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Dichao-Liu/CMAL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月4日(星期六) 晚上6:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Dichao-Liu/CMAL] 我运行train_FGVC_Aircraft_ResNet50.py报错说我显存不够，但是我16g显存和24g都运行了还是这样 (Issue #4)





 
你好，我刚才试了一下。我用的11g的1080ti，代码用的是直接下载的我这个GitHub的代码，并不会报现存不够的错。请问是不是Batch Size被我的原代码里的大。

**Comment by lypliuyouping** [comment]
代码我没改的，就用了官网的数据集直接报错显存不足







1449917271
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Dichao-Liu/CMAL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月4日(星期六) 晚上6:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Dichao-Liu/CMAL] 我运行train_FGVC_Aircraft_ResNet50.py报错说我显存不够，但是我16g显存和24g都运行了还是这样 (Issue #4)





 
你好，我刚才试了一下。我用的11g的1080ti，代码用的是直接下载的我这个GitHub的代码，并不会报现存不够的错。请问是不是Batch Size被我的原代码里的大。

**Comment by Dichao-Liu** [comment]
我看了一下你的报错。主代码里遭遇显存不足是在netp = torch.nn.DataParallel(net, device_ids=[0])这一段。运行该段的时候，pytorch的代码返回了return self._apply(lambda t: t.cuda(device)) RuntimeError: CUDA error: out of memory 的报错，也就是在加载模型的阶段就遇到了显存不足，而非在运算的时候。这显然不是一个常见的会出现显存不足的案例。我查了一下，我觉得你可以参照[这个博客](https://blog.csdn.net/Asunnayy/article/details/114871993)*（这个案例中，pytorch报错的位置跟你的貌似一样），或者其他遇到类似问题的人的解决方案。
